knife4j:
  enable: true
  openapi:
    title: 脑筋急转弯api文档
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.zjgsu.hxy.AI_brain_teasers.controller

ai:
  apiKey: 782e9281-7e8a-41ad-b297-6c838f75f39b
