knife4j:
  enable: true
  openapi:
    title: 脑筋急转弯api文档
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.tfzhang.ainaojin.controller

ai:
  apiKey: ${AI_API_KEY:}
