knife4j:
  enable: true
  openapi:
    title: 脑筋急转弯api文档
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.zjgsu.hxy.AI_brain_teasers.controller

deepseek:
  # api-key: ${DEEPSEEK_API_KEY:}
  api-key: sk-c2a3b2efff4a429f85e657fd4be02775
  base-url: https://api.deepseek.com/v1
  model: deepseek-chat

# Spring 配置
spring:
  application:
    name: AI-brain-teasers
  profiles:
    active: dev

# 日志配置（用于调试）
logging:
  level:
    com.zjgsu.hxy.AI_brain_teasers: DEBUG
